export const GET_SENT_TEMPLATES = 'GET_SENT_TEMPLATES'

export const ADD_SENT_TEMPLATE_FOLDER = 'ADD_SENT_TEMPLATE_FOLDER'
export const DELETE_SENT_TEMPLATE_FOLDER = 'DELETE_SENT_TEMPLATE_FOLDER'
export const UPDATE_SENT_TEMPLATE_FOLDER = 'UPDATE_SENT_TEMPLATE_FOLDER'
